// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN56Ea0SO-BqOm9FgMhV5YJ1wAZevYyKw',
    appId: '1:341416861365:web:19869900f91df4bccbe8fc',
    messagingSenderId: '341416861365',
    projectId: 'flutterapp-a3886',
    authDomain: 'flutterapp-a3886.firebaseapp.com',
    storageBucket: 'flutterapp-a3886.firebasestorage.app',
    measurementId: 'G-G0VQEG758Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjqlJL26vpBJShQ0J5J1ZFNySGOcV0mds',
    appId: '1:341416861365:android:51078de6bee2adafcbe8fc',
    messagingSenderId: '341416861365',
    projectId: 'flutterapp-a3886',
    storageBucket: 'flutterapp-a3886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY6Yk2122eMer8nctwUNz-DvNw_Mo9lIE',
    appId: '1:341416861365:ios:a2ad72369681482dcbe8fc',
    messagingSenderId: '341416861365',
    projectId: 'flutterapp-a3886',
    storageBucket: 'flutterapp-a3886.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY6Yk2122eMer8nctwUNz-DvNw_Mo9lIE',
    appId: '1:341416861365:ios:a2ad72369681482dcbe8fc',
    messagingSenderId: '341416861365',
    projectId: 'flutterapp-a3886',
    storageBucket: 'flutterapp-a3886.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN56Ea0SO-BqOm9FgMhV5YJ1wAZevYyKw',
    appId: '1:341416861365:web:ec98b1639e6238dccbe8fc',
    messagingSenderId: '341416861365',
    projectId: 'flutterapp-a3886',
    authDomain: 'flutterapp-a3886.firebaseapp.com',
    storageBucket: 'flutterapp-a3886.firebasestorage.app',
    measurementId: 'G-0GVS9BWNSQ',
  );
}
